# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Devottam\DL\__UI\\DLTrackerUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1500, 900)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.digital_lync_tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.digital_lync_tabWidget.setFont(font)
        self.digital_lync_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.digital_lync_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.digital_lync_tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.digital_lync_tabWidget.setDocumentMode(False)
        self.digital_lync_tabWidget.setTabsClosable(False)
        self.digital_lync_tabWidget.setMovable(True)
        self.digital_lync_tabWidget.setObjectName(_fromUtf8("digital_lync_tabWidget"))
        self.track_progress = QtGui.QWidget()
        self.track_progress.setObjectName(_fromUtf8("track_progress"))
        self.gridLayout_2 = QtGui.QGridLayout(self.track_progress)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.comboBox_3 = QtGui.QComboBox(self.track_progress)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.comboBox_4 = QtGui.QComboBox(self.track_progress)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_3.addWidget(self.comboBox_4)
        self.comboBox = QtGui.QComboBox(self.track_progress)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_3 = QtGui.QPushButton(self.track_progress)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.track_progress)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.listWidget_3 = QtGui.QListWidget(self.track_progress)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget_3)
        self.listWidget_4 = QtGui.QListWidget(self.track_progress)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.tableWidget_2 = QtGui.QTableWidget(self.track_progress)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStrikeOut(True)
        item.setFont(font)
        self.tableWidget_2.setItem(0, 5, item)
        self.horizontalLayout_4.addWidget(self.tableWidget_2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.digital_lync_tabWidget.addTab(self.track_progress, _fromUtf8(""))
        self.schedule_batch = QtGui.QWidget()
        self.schedule_batch.setObjectName(_fromUtf8("schedule_batch"))
        self.digital_lync_tabWidget.addTab(self.schedule_batch, _fromUtf8(""))
        self.registration = QtGui.QWidget()
        self.registration.setObjectName(_fromUtf8("registration"))
        self.gridLayout_3 = QtGui.QGridLayout(self.registration)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.student_radioButton = QtGui.QRadioButton(self.registration)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.student_radioButton.setFont(font)
        self.student_radioButton.setObjectName(_fromUtf8("student_radioButton"))
        self.verticalLayout.addWidget(self.student_radioButton)
        self.mentor_radioButton = QtGui.QRadioButton(self.registration)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.mentor_radioButton.setFont(font)
        self.mentor_radioButton.setObjectName(_fromUtf8("mentor_radioButton"))
        self.verticalLayout.addWidget(self.mentor_radioButton)
        self.horizontalLayout_30.addLayout(self.verticalLayout)
        self.generateID_pushButton = QtGui.QPushButton(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateID_pushButton.sizePolicy().hasHeightForWidth())
        self.generateID_pushButton.setSizePolicy(sizePolicy)
        self.generateID_pushButton.setObjectName(_fromUtf8("generateID_pushButton"))
        self.horizontalLayout_30.addWidget(self.generateID_pushButton)
        self.horizontalLayout_30.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.id_label = QtGui.QLabel(self.registration)
        self.id_label.setObjectName(_fromUtf8("id_label"))
        self.horizontalLayout_6.addWidget(self.id_label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.studentID_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentID_lineEdit.sizePolicy().hasHeightForWidth())
        self.studentID_lineEdit.setSizePolicy(sizePolicy)
        self.studentID_lineEdit.setObjectName(_fromUtf8("studentID_lineEdit"))
        self.horizontalLayout_6.addWidget(self.studentID_lineEdit)
        self.loadID_pushButton = QtGui.QPushButton(self.registration)
        self.loadID_pushButton.setObjectName(_fromUtf8("loadID_pushButton"))
        self.horizontalLayout_6.addWidget(self.loadID_pushButton)
        self.remove_student_checkBox = QtGui.QCheckBox(self.registration)
        self.remove_student_checkBox.setObjectName(_fromUtf8("remove_student_checkBox"))
        self.horizontalLayout_6.addWidget(self.remove_student_checkBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.line = QtGui.QFrame(self.registration)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.student_fname_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_fname_lineEdit.sizePolicy().hasHeightForWidth())
        self.student_fname_lineEdit.setSizePolicy(sizePolicy)
        self.student_fname_lineEdit.setObjectName(_fromUtf8("student_fname_lineEdit"))
        self.horizontalLayout_7.addWidget(self.student_fname_lineEdit)
        self.fname_valid_label = QtGui.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.fname_valid_label.setFont(font)
        self.fname_valid_label.setObjectName(_fromUtf8("fname_valid_label"))
        self.horizontalLayout_7.addWidget(self.fname_valid_label)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.registration)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem6 = QtGui.QSpacerItem(93, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.student_lname_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_lname_lineEdit.sizePolicy().hasHeightForWidth())
        self.student_lname_lineEdit.setSizePolicy(sizePolicy)
        self.student_lname_lineEdit.setObjectName(_fromUtf8("student_lname_lineEdit"))
        self.horizontalLayout.addWidget(self.student_lname_lineEdit)
        self.lname_valid_label = QtGui.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lname_valid_label.setFont(font)
        self.lname_valid_label.setObjectName(_fromUtf8("lname_valid_label"))
        self.horizontalLayout.addWidget(self.lname_valid_label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_2 = QtGui.QLabel(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_14.addWidget(self.label_2)
        spacerItem8 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.dob_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dob_lineEdit.sizePolicy().hasHeightForWidth())
        self.dob_lineEdit.setSizePolicy(sizePolicy)
        self.dob_lineEdit.setObjectName(_fromUtf8("dob_lineEdit"))
        self.horizontalLayout_14.addWidget(self.dob_lineEdit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_3 = QtGui.QLabel(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        spacerItem10 = QtGui.QSpacerItem(85, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.qualification_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualification_lineEdit.sizePolicy().hasHeightForWidth())
        self.qualification_lineEdit.setSizePolicy(sizePolicy)
        self.qualification_lineEdit.setObjectName(_fromUtf8("qualification_lineEdit"))
        self.horizontalLayout_13.addWidget(self.qualification_lineEdit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.profession_label = QtGui.QLabel(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profession_label.sizePolicy().hasHeightForWidth())
        self.profession_label.setSizePolicy(sizePolicy)
        self.profession_label.setObjectName(_fromUtf8("profession_label"))
        self.horizontalLayout_12.addWidget(self.profession_label)
        spacerItem12 = QtGui.QSpacerItem(97, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.profession_lineEdit = QtGui.QLineEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profession_lineEdit.sizePolicy().hasHeightForWidth())
        self.profession_lineEdit.setSizePolicy(sizePolicy)
        self.profession_lineEdit.setObjectName(_fromUtf8("profession_lineEdit"))
        self.horizontalLayout_12.addWidget(self.profession_lineEdit)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.registration)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        spacerItem14 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.address_textEdit = QtGui.QTextEdit(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_textEdit.sizePolicy().hasHeightForWidth())
        self.address_textEdit.setSizePolicy(sizePolicy)
        self.address_textEdit.setObjectName(_fromUtf8("address_textEdit"))
        self.horizontalLayout_11.addWidget(self.address_textEdit)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.registration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem16 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.mob_number_lineEdit = QtGui.QLineEdit(self.registration)
        self.mob_number_lineEdit.setObjectName(_fromUtf8("mob_number_lineEdit"))
        self.horizontalLayout_10.addWidget(self.mob_number_lineEdit)
        self.mob_num_label = QtGui.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.mob_num_label.setFont(font)
        self.mob_num_label.setObjectName(_fromUtf8("mob_num_label"))
        self.horizontalLayout_10.addWidget(self.mob_num_label)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.registration)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem18 = QtGui.QSpacerItem(112, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.emailid_lineEdit = QtGui.QLineEdit(self.registration)
        self.emailid_lineEdit.setObjectName(_fromUtf8("emailid_lineEdit"))
        self.horizontalLayout_9.addWidget(self.emailid_lineEdit)
        self.email_id_label = QtGui.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.email_id_label.setFont(font)
        self.email_id_label.setObjectName(_fromUtf8("email_id_label"))
        self.horizontalLayout_9.addWidget(self.email_id_label)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.bar_graph_label = QtGui.QLabel(self.registration)
        self.bar_graph_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_graph_label.sizePolicy().hasHeightForWidth())
        self.bar_graph_label.setSizePolicy(sizePolicy)
        self.bar_graph_label.setMinimumSize(QtCore.QSize(0, 240))
        self.bar_graph_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.bar_graph_label.setFrameShape(QtGui.QFrame.Panel)
        self.bar_graph_label.setText(_fromUtf8(""))
        self.bar_graph_label.setObjectName(_fromUtf8("bar_graph_label"))
        self.verticalLayout_6.addWidget(self.bar_graph_label)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.course_label = QtGui.QLabel(self.registration)
        self.course_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.course_label.setAlignment(QtCore.Qt.AlignCenter)
        self.course_label.setObjectName(_fromUtf8("course_label"))
        self.verticalLayout_8.addWidget(self.course_label)
        self.courses_listWidget = QtGui.QListWidget(self.registration)
        self.courses_listWidget.setProperty("showDropIndicator", True)
        self.courses_listWidget.setDragEnabled(False)
        self.courses_listWidget.setDragDropOverwriteMode(False)
        self.courses_listWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.courses_listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.courses_listWidget.setObjectName(_fromUtf8("courses_listWidget"))
        self.verticalLayout_8.addWidget(self.courses_listWidget)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem20)
        self.add_course_pushButton = QtGui.QPushButton(self.registration)
        self.add_course_pushButton.setObjectName(_fromUtf8("add_course_pushButton"))
        self.verticalLayout_9.addWidget(self.add_course_pushButton)
        self.remove_course_pushButton = QtGui.QPushButton(self.registration)
        self.remove_course_pushButton.setObjectName(_fromUtf8("remove_course_pushButton"))
        self.verticalLayout_9.addWidget(self.remove_course_pushButton)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem21)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.course_opted_label = QtGui.QLabel(self.registration)
        self.course_opted_label.setAlignment(QtCore.Qt.AlignCenter)
        self.course_opted_label.setObjectName(_fromUtf8("course_opted_label"))
        self.verticalLayout_7.addWidget(self.course_opted_label)
        self.course_opted_listWidget = QtGui.QListWidget(self.registration)
        self.course_opted_listWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.course_opted_listWidget.setObjectName(_fromUtf8("course_opted_listWidget"))
        self.verticalLayout_7.addWidget(self.course_opted_listWidget)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.update_pushButton = QtGui.QPushButton(self.registration)
        self.update_pushButton.setObjectName(_fromUtf8("update_pushButton"))
        self.horizontalLayout_16.addWidget(self.update_pushButton)
        self.reset_pushButton = QtGui.QPushButton(self.registration)
        self.reset_pushButton.setObjectName(_fromUtf8("reset_pushButton"))
        self.horizontalLayout_16.addWidget(self.reset_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.digital_lync_tabWidget.addTab(self.registration, _fromUtf8(""))
        self.gridLayout.addWidget(self.digital_lync_tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.digital_lync_tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Lync Tracker", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "COURSE", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "TRAINER", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "STUDENT", None))
        self.pushButton_3.setText(_translate("MainWindow", "Track", None))
        self.pushButton_4.setText(_translate("MainWindow", "Reset", None))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_3.item(3)
        item.setText(_translate("MainWindow", "New Item", None))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_4.item(1)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_4.item(2)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_4.item(3)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget_4.item(4)
        item.setText(_translate("MainWindow", "New Item", None))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "DL_PY_001", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Trainer", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Branch", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Date", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End Date", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Current Topic", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Hours Completed", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Batch Shift Timing", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Progress", None))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.digital_lync_tabWidget.setTabText(self.digital_lync_tabWidget.indexOf(self.track_progress), _translate("MainWindow", "Track Progress", None))
        self.digital_lync_tabWidget.setTabText(self.digital_lync_tabWidget.indexOf(self.schedule_batch), _translate("MainWindow", "Schedule Batch", None))
        self.student_radioButton.setText(_translate("MainWindow", "For Student", None))
        self.mentor_radioButton.setText(_translate("MainWindow", "For Mentor", None))
        self.generateID_pushButton.setText(_translate("MainWindow", "Generate Student ID", None))
        self.id_label.setText(_translate("MainWindow", "Student ID", None))
        self.loadID_pushButton.setText(_translate("MainWindow", "Load ID", None))
        self.remove_student_checkBox.setText(_translate("MainWindow", "Remove Student", None))
        self.label.setText(_translate("MainWindow", "First Name", None))
        self.fname_valid_label.setText(_translate("MainWindow", "mandatory field", None))
        self.label_9.setText(_translate("MainWindow", "Last Name", None))
        self.lname_valid_label.setText(_translate("MainWindow", "mandatory field", None))
        self.label_2.setText(_translate("MainWindow", "Date of Birth ", None))
        self.label_3.setText(_translate("MainWindow", "Qualification", None))
        self.profession_label.setText(_translate("MainWindow", "Profession", None))
        self.label_5.setText(_translate("MainWindow", "Communication Address", None))
        self.label_6.setText(_translate("MainWindow", "Mobilel Number", None))
        self.mob_num_label.setText(_translate("MainWindow", "mandatory field", None))
        self.label_7.setText(_translate("MainWindow", "Email ID", None))
        self.email_id_label.setText(_translate("MainWindow", "mandatory field", None))
        self.course_label.setText(_translate("MainWindow", "Courses Available", None))
        self.add_course_pushButton.setText(_translate("MainWindow", ">>", None))
        self.remove_course_pushButton.setText(_translate("MainWindow", "<<", None))
        self.course_opted_label.setText(_translate("MainWindow", "Courses Opted", None))
        self.update_pushButton.setText(_translate("MainWindow", "Update", None))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset", None))
        self.digital_lync_tabWidget.setTabText(self.digital_lync_tabWidget.indexOf(self.registration), _translate("MainWindow", "Registration", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

